use std::{fmt, path::Path};

#[derive(Eq, Hash, PartialEq, Debug, Clone)]
pub enum Language {
    Arduino,
    Assembly,
    Bash,
    Batchfile,
    C,
    Clojure,
    CMake,
    CSharp,
    Cpp,
    Css,
    Dart,
    Dockerfile,
    Go,
    Haskell,
    Html,
    Java,
    Js,
    Json,
    JupyterNotebook,
    Kotlin,
    Lua,
    Makefile,
    Markdown,
    OCaml,
    Pascal,
    Perl,
    Php,
    Poweshell,
    Python,
    Ruby,
    Rust,
    Sass,
    Scala,
    Scss,
    Shell,
    Svelte,
    Swift,
    Toml,
    Ts,
    Vue,
    Yaml,
    Xml,
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::Arduino => write!(f, "Arduino"),
            Self::Assembly => write!(f, "Assembly"),
            Self::Bash => write!(f, "Bash"),
            Self::Batchfile => write!(f, "Batchfile"),
            Self::C => write!(f, "C"),
            Self::Clojure => write!(f, "Clojure"),
            Self::CMake => write!(f, "CMake"),
            Self::CSharp => write!(f, "C#"),
            Self::Cpp => write!(f, "C++"),
            Self::Css => write!(f, "CSS"),
            Self::Dart => write!(f, "Dart"),
            Self::Dockerfile => write!(f, "Dockerfile"),
            Self::Go => write!(f, "Go"),
            Self::Haskell => write!(f, "Haskell"),
            Self::Html => write!(f, "HTML"),
            Self::Java => write!(f, "Java"),
            Self::Js => write!(f, "Javascript"),
            Self::Json => write!(f, "JSON"),
            Self::JupyterNotebook => write!(f, "Jupyter Notebook"),
            Self::Kotlin => write!(f, "Kotlin"),
            Self::Lua => write!(f, "Lua"),
            Self::Makefile => write!(f, "Makefile"),
            Self::Markdown => write!(f, "Markdown"),
            Self::OCaml => write!(f, "OCaml"),
            Self::Pascal => write!(f, "Pascal"),
            Self::Perl => write!(f, "Perl"),
            Self::Php => write!(f, "PhP"),
            Self::Poweshell => write!(f, "Powershell"),
            Self::Python => write!(f, "Python"),
            Self::Ruby => write!(f, "Ruby"),
            Self::Rust => write!(f, "Rust"),
            Self::Sass => write!(f, "SASS"),
            Self::Scala => write!(f, "Scala"),
            Self::Scss => write!(f, "SCSS"),
            Self::Shell => write!(f, "Shell"),
            Self::Svelte => write!(f, "Svelte"),
            Self::Swift => write!(f, "Swift"),
            Self::Toml => write!(f, "TOML"),
            Self::Ts => write!(f, "Typescript"),
            Self::Vue => write!(f, "Vue"),
            Self::Yaml => write!(f, "YAML"),
            Self::Xml => write!(f, "XML"),
        }
    }
}

impl Language {
    pub fn from_path(path: &Path) -> Option<Self> {
        if let Some(extension) = path.extension()
            && let Some(language) = extension.to_str()
        {
            let language = match language {
                "ino" => Self::Arduino,
                "asm" | "a51" | "inc" | "nasm" => Self::Assembly,
                "bash" => Self::Bash,
                "bat" | "cmd" => Self::Batchfile,
                "c" | "h" => Self::C,
                "clj" => Self::Clojure,
                "cmake" => Self::CMake,
                "cs" | "cake" | "cshtml" | "csx" => Self::CSharp,
                "cpp" | "c++" | "cc" | "cp" | "cxx" | "hh" | "hpp" | "hxx" => Self::Cpp,
                "css" => Self::Css,
                "dart" => Self::Dart,
                "dockerfile" => Self::Dockerfile,
                "go" => Self::Go,
                "hs" | "hsc" => Self::Haskell,
                "html" => Self::Html,
                "java" => Self::Java,
                "js" => Self::Js,
                "json" => Self::Json,
                "ipynb" => Self::JupyterNotebook,
                "kt" | "kts" | "ktm" => Self::Kotlin,
                "lua" => Self::Lua,
                "mk" | "mkfile" => Self::Makefile,
                "md" | "markdown" => Self::Markdown,
                "ml" | "mli" => Self::OCaml,
                "pas" => Self::Pascal,
                "pl" | "perl" => Self::Perl,
                "php" => Self::Php,
                "ps1" | "psd1" | "psm1" => Self::Poweshell,
                "py" => Self::Python,
                "rb" | "ruby" => Self::Ruby,
                "rs" => Self::Rust,
                "sass" => Self::Sass,
                "scala" | "sc" => Self::Scala,
                "scss" => Self::Scss,
                "sh" => Self::Shell,
                "Svelte" | "svelte" => Self::Svelte,
                "swift" => Self::Swift,
                "toml" => Self::Toml,
                "ts" | "tsx" => Self::Ts,
                "vue" => Self::Vue,
                "yaml" | "yml" => Self::Yaml,
                "xml" => Self::Xml,
                &_ => return None,
            };
            Some(language)
        } else {
            None
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            Self::Arduino => "\u{e733}",
            Self::Assembly => "\u{e6ab}",
            Self::Bash | Self::Shell => "\u{e760}",
            Self::C => "\u{e61e}",
            Self::Clojure => "\u{e790}",
            Self::CMake => "\u{e794}",
            Self::Cpp => "\u{e61d}",
            Self::CSharp => "\u{e7b2}",
            Self::Css => "\u{e6b8}",
            Self::Dart => "\u{e798}",
            Self::Dockerfile => "\u{e7b0}",
            Self::Go => "\u{f07d3}",
            Self::Haskell => "\u{e777}",
            Self::Html => "\u{e736}",
            Self::Java => "\u{e738}",
            Self::Js => "\u{e781}",
            Self::Json => "\u{eb0f}",
            Self::JupyterNotebook => "\u{e80f}",
            Self::Kotlin => "\u{e634}",
            Self::Lua => "\u{e826}",
            Self::Makefile => "\u{e673}",
            Self::Markdown => "\u{e73e}",
            Self::OCaml => "\u{e84e}",
            Self::Perl => "\u{e769}",
            Self::Php => "\u{e73d}",
            Self::Poweshell => "\u{e86c}",
            Self::Python => "\u{e73c}",
            Self::Ruby => "\u{e739}",
            Self::Rust => "\u{e7a8}",
            Self::Sass => "\u{e74b}",
            Self::Scala => "\u{e737}",
            Self::Svelte => "\u{e8b7}",
            Self::Swift => "\u{e755}",
            Self::Toml => "\u{e6b2}",
            Self::Ts => "\u{e69d}",
            Self::Vue => "\u{e6a0}",
            Self::Yaml => "\u{e8eb}",
            Self::Xml => "\u{e8ea}",
            _ => "-",
        }
    }
}
