use std::fmt;

#[derive(Eq, Hash, PartialEq, Debug, Clone)]
pub enum Language {
    Arduino,
    Assembly,
    Bash,
    Batchfile,
    C,
    Clojure,
    CMake,
    CSharp,
    Cpp,
    Css,
    Dart,
    Go,
    Haskell,
    Html,
    Java,
    Js,
    Json,
    JupyterNotebook,
    Kotlin,
    Lua,
    Makefile,
    Markdown,
    Pascal,
    Perl,
    Php,
    Python,
    Ruby,
    Rust,
    Scala,
    Shell,
    Svelte,
    Swift,
    Toml,
    Ts,
    Others,
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::Arduino => write!(f, "Arduino"),
            Self::Assembly => write!(f, "Assembly"),
            Self::Bash => write!(f, "Bash"),
            Self::Batchfile => write!(f, "Batchfile"),
            Self::C => write!(f, "C"),
            Self::Clojure => write!(f, "Clojure"),
            Self::CMake => write!(f, "CMake"),
            Self::CSharp => write!(f, "C#"),
            Self::Cpp => write!(f, "C++"),
            Self::Css => write!(f, "CSS"),
            Self::Dart => write!(f, "Dart"),
            Self::Go => write!(f, "Go"),
            Self::Haskell => write!(f, "Haskell"),
            Self::Html => write!(f, "HTML"),
            Self::Java => write!(f, "Java"),
            Self::Js => write!(f, "Javascript"),
            Self::Json => write!(f, "JSON"),
            Self::JupyterNotebook => write!(f, "Jupyter Notebook"),
            Self::Kotlin => write!(f, "Kotlin"),
            Self::Lua => write!(f, "Lua"),
            Self::Makefile => write!(f, "Makefile"),
            Self::Markdown => write!(f, "Markdown"),
            Self::Pascal => write!(f, "Pascal"),
            Self::Perl => write!(f, "Perl"),
            Self::Php => write!(f, "PhP"),
            Self::Python => write!(f, "Python"),
            Self::Ruby => write!(f, "Ruby"),
            Self::Rust => write!(f, "Rust"),
            Self::Scala => write!(f, "Scala"),
            Self::Shell => write!(f, "Shell"),
            Self::Svelte => write!(f, "Svelte"),
            Self::Swift => write!(f, "Swift"),
            Self::Toml => write!(f, "TOML"),
            Self::Ts => write!(f, "Typescript"),
            Self::Others => write!(f, "others"),
        }
    }
}

impl Language {
    pub fn from_extension(extension: &str) -> Self {
        match extension {
            "ino" => Self::Arduino,
            "asm" | "a51" | "inc" | "nasm" => Self::Assembly,
            "bash" => Self::Bash,
            "bat" | "cmd" => Self::Batchfile,
            "c" | "h" => Self::C,
            "clj" => Self::Clojure,
            "cmake" => Self::CMake,
            "cs" | "cake" | "cshtml" | "csx" => Self::CSharp,
            "cpp" | "c++" | "cc" | "cp" | "cxx" | "hh" | "hpp" | "hxx" => Self::Cpp,
            "css" => Self::Css,
            "dart" => Self::Dart,
            "go" => Self::Go,
            "hs" | "hsc" => Self::Haskell,
            "html" => Self::Html,
            "java" => Self::Java,
            "js" => Self::Js,
            "json" => Self::Json,
            "ipynb" => Self::JupyterNotebook,
            "kt" => Self::Kotlin,
            "lua" => Self::Lua,
            "mk" | "mkfile" => Self::Makefile,
            "md" | "markdown" => Self::Markdown,
            "pas" => Self::Pascal,
            "pl" | "perl" => Self::Perl,
            "php" => Self::Php,
            "py" => Self::Python,
            "rb" | "ruby" => Self::Ruby,
            "rs" => Self::Rust,
            "scala" | "sc" => Self::Scala,
            "sh" => Self::Shell,
            "Svelte" | "svelte" => Self::Svelte,
            "swift" => Self::Swift,
            "toml" => Self::Toml,
            "ts" | "tsx" => Self::Ts,
            _ => Self::Others,
        }
    }
}
